apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-001
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Mi
  storageClassName: "local"
  hostPath:
    path: /usr/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: pvc-001
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: "local"

